version: "3"
services:
  couchbase1:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: couchbase1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
